CREATE TABLE bs_remind_config
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remind_start_time timestamp              NULL,
    remind_end_time   timestamp              NULL,
    create_time       timestamp              NULL,
    tenant_id         BIGINT                NULL,
    user_id           BIGINT                NULL
);

ALTER TABLE bs_remind_config
    ADD CONSTRAINT FK_BS_REMIND_CONFIG_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES bs_tenant (id);

ALTER TABLE bs_remind_config
    ADD CONSTRAINT FK_BS_REMIND_CONFIG_ON_USER FOREIGN KEY (user_id) REFERENCES bs_user (id);