CREATE TABLE bs_user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255)          NULL,
    password  VARCHAR(255)          NULL,
    tenant_id BIGINT                NULL
);

ALTER TABLE bs_user
    ADD CONSTRAINT FK_BS_USER_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES bs_tenant (id);