CREATE TABLE bs_tenant
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255)          NULL,
    tenant_id VARCHAR(255)          NULL,
    CONSTRAINT pk_bs_tenant PRIMARY KEY (id)
);